require:
  rubocop-rspec

# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

inherit_mode:
  merge:
    - Exclude

RSpec/SpecFilePathFormat:
  CustomTransform:
    OmniAuth: omniauth

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
