version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      - forms-api-pgdata:/var/lib/postgresql/data/
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
volumes:
  forms-api-pgdata: {}
