local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

forms_deploy:
  service: S3
  endpoint: "http://localhost:4566"
  access_key_id: test
  secret_access_key: test
  region: us-east-1
  bucket: test
  force_path_style: true
