name: "Review apps: on PR close"
on:
  pull_request:
    types: [closed]

concurrency:
  group: "review-apps-pr-${{ github.event.pull_request.number }}"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  delete-review-app:
    name: Delete review app
    uses: govuk-forms/forms-deploy/.github/workflows/reusable-review_apps_on_pr_close.yml@main
    with:
      app-name: forms-admin
